feat: use statebag for alcohol level
Qbox-project/qbx_smallresources pull request #79
Opened 2024-02-15 23:04 UTC by TonybynMp4

## Description
For my awesome [qbx_alcoholism ](https://github.com/tonybynmp4/qbx_alcoholism) resource

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-02-16 02:24 UTC, lwhp requested changes

2024-02-16 02:24 UTC, lwhp commented on server/consumables.lua
> +        Player(source).state:set('alcohol', (Player(source).state.alcohol or 0) + params.alcoholLevel, true)
```suggestion
        local playerState = Player(source).state
        playerState:set('alcohol', (playerState.alcohol or 0) + params.alcoholLevel, true)
```
Gotta change this g

2024-02-16 14:59 UTC, bicatcho11 commented
hi why not using function CheckPlayerData(source, playerData) ?for save alcohol level

2024-02-16 15:02 UTC, BerkieBb commented
> hi why not using function CheckPlayerData(source, playerData) ?for save alcohol level

CheckPlayerData is for initializing PlayerData, it's an internal function not meant for anything else

2024-02-16 15:08 UTC, TonybynMp4 commented
I think i'll repurpose this pr to yeet alcohol from smallresources tbh,
With qbx_alcoholism we can just have the alcohol consumables there

2024-02-19 12:03 UTC, BerkieBb approved these changes

2024-02-22 19:04 UTC, TonybynMp4 commented
Using qbx_alcoholism isn't planned so i'll close this.

2024-02-22 19:04 UTC, closed without merging