Update client.lua
Qbox-project/qbx_smallresources pull request #97
Opened 2024-04-29 23:21 UTC by Mesrine67

add lib.addKeybind()

## Description

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-04-29 23:45 UTC, Manason requested changes

2024-04-29 23:45 UTC, Manason commented on qbx_cruise/client.lua
> +local keybindCruiseControl = lib.addKeybind({name = 'toggle_cruise_control', description = 'Activer/Désactiver le régulateur de vitesse', defaultKey = 'Y',
make a locale

2024-04-29 23:45 UTC, Manason commented on qbx_cruise/client.lua
> +        if cache.seat == -1 then
swap these two lines

2024-05-02 00:06 UTC, Manason approved these changes

2024-05-02 15:30 UTC, Mesrine67 reviewed
Up locale

2024-05-02 19:36 UTC, KostaZx approved these changes

2024-05-02 19:36 UTC, merged